import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Awesome Next App",
  description: "Generated by iam454",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <h1>
          <Link href="/">Hello, Next.js!</Link>
        </h1>
        {children}
        <ol>
          <li>
            <Link href="/create">Create</Link>
          </li>
          <li>
            <Link href="/read/123">Read</Link>
          </li>
        </ol>
      </body>
    </html>
  );
}
