import Link from "next/link";
import "./globals.css";
import Control from "./Control";

export const metadata = {
  title: "Awesome Next App",
  description: "Generated by iam454",
};

export default async function RootLayout({ children }) {
  const res = await fetch("http://localhost:9999/topics", {
    cache: "no-store",
  });
  const topics = await res.json();
  return (
    <html lang="ko">
      <body>
        <h1>
          <Link href="/">Hello, Next.js!</Link>
        </h1>
        <ol>
          {topics.map((topic) => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
